var images = [
	'<img src="images/img1.png">', //picked
	'<img src="images/img1.png">',
	'<img src="images/img2.png">',
	'<img src="images/img2.png">',
	'<img src="images/img3.png">', //picked
	'<img src="images/img3.png">',
	'<img src="images/img4.png">',
	'<img src="images/img4.png">',
	'<img src="images/img5.png">',
	'<img src="images/img5.png">',
	'<img src="images/img6.png">',
	'<img src="images/img6.png">',
	'<img src="images/img7.png">',
	'<img src="images/img7.png">',
	'<img src="images/img8.png">',
	'<img src="images/img8.png">',
	'<img src="images/img9.png">',
	'<img src="images/img9.png">',
	'<img src="images/img10.png">',
	'<img src="images/img10.png">',
];